# Define risky keywords and their descriptions
RISKY_KEYWORDS = {
    "sudo": "Requires elevated permissions.",
    "rm": "Can delete files or directories.",
    "rm -rf": "Can delete files or directories recursively without confirmation.",
    "dd": "Can overwrite disk data.",
    "mkfs": "Can format a disk or partition.",
    "chmod 777": "Grants full permissions to everyone, which can be a security risk.",
    "chown": "Changes file ownership, which can affect system functionality.",
    "iptables": "Modifies firewall rules, which can disrupt network connectivity.",
    "systemctl": "Starts, stops, or restarts system services.",
    "shutdown": "Shuts down the system.",
    "reboot": "Reboots the system.",
    "kill": "Terminates processes, which can cause instability.",
    "wget": "Downloads files, which can execute untrusted scripts.",
    "curl": "Fetches data, which can execute untrusted scripts.",
    "scp": "Transfers files, which can overwrite data.",
    "mv": "Moves files, which can overwrite data.",
    "dd if": "Can overwrite disk data.",
    "fdisk": "Modifies disk partitions.",
    "parted": "Modifies disk partitions.",
    "mount": "Mounts filesystems, which can affect system stability.",
    "umount": "Unmounts filesystems, which can affect system stability.",
    "export": "Modifies environment variables, which can affect system behavior.",
    "unset": "Removes environment variables, which can affect system behavior.",
    "alias": "Creates command aliases, which can override default commands.",
    "source": "Executes scripts, which can modify the current shell environment.",
    "y/n": "Prompts for confirmation, which may indicate a risky operation.",
    "--force": "Forces an operation, which can bypass safety checks.",
    "--yes": "Automatically confirms prompts, which can lead to unintended actions."
}